<?php
$collection = $block->getCollection();
?>
<br>
<hr>
<br>
<h2>Employee Details</h2>
<table class="data table" id="test-data-table">
    <thead>
        <tr>
            <th>EmployeeID</th>
            <th>FirstName</th>
            <th>LastName</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($collection as $key => $data): ?>
            <tr>
                <td><?php echo $data['employee_id'];?></td>
                <td><?php echo $data['first_name'];?></td>
                <td><?php echo $data['last_name'];?></td>
                <td><?php echo $data['email_id'];?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>